version: '3.5'
services:
  merlin-app:
    image: merlin-app
    #build: .
    #restart: always
    ports:
      - 8000:8000
      - 80:80
    depends_on:
      - merlin-db
    environment:
      DATABASE_URL: "postgres://merlin@merlin-db/merlin"
      PORT: "80"
  merlin-db:
    image: postgres
    #restart: always
    ports:
    - "5432:5432"
    volumes:
    - merlindb-data:/var/lib/postgresql/data/merlin
    environment:
      PGDATA: /var/lib/postgresql/data/merlin
      POSTGRES_DB: merlin
      POSTGRES_USER: merlin
volumes:
  merlindb-data: {}